// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const prismaurl = process.env.DIRECT_URL || process.env.DATABASE_URL;

if(!prismaurl){
  throw new Error(
    'DIRECT_URL or DATABASE_URL must be set in .env for prisma CLI commands',
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'tsx prisma/seed.ts'
  },
  datasource: {
    url: prismaurl,
  },
});
